name: cnvsoft
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at http's://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1136996

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  data_connection_checker_tv: ^0.3.5-nullsafety 
  http_mock_adapter: ^0.3.2
  carousel_slider: 4.0.0 
  qr_code_scanner: 1.0.1
  phone_number: 0.11.0+2
  intl: 0.17.0
  extended_image: 4.1.0
  crypto: 3.0.1
  http_extensions: 1.0.0 
  url_launcher: 6.0.9 
  webview_flutter: 2.0.10
  flutter_svg: 0.22.0
  firebase_auth: 3.0.1
  firebase_core: 1.4.0
  firebase_messaging: 10.0.4
  flutter_local_notifications: 9.3.2
  device_info: 2.0.2 
  dio: 4.0.0 
  connectivity: 3.0.6
  flutter_widget_from_html: 0.6.1
  cached_network_image: 3.1.0 
  provider: 6.0.1 
  image_picker: 0.8.2
  shared_preferences: 2.0.13
  flutter_keyboard_visibility: 5.0.3
  rxdart: 0.27.3
  exif: 3.0.0 
  flutter_vibrate: 1.1.0 
  package_info: 2.0.2
  flutter_image_compress: 1.1.0
  flutter_json_view: 0.2.1 
  permission_handler: 6.0.0
  event_bus: 2.0.0
  image_cropper: 1.4.1
  shimmer: 2.0.0
  transparent_image: 2.0.0
  camera: 0.8.1+7
  dart_ipify: 1.1.0
  country_code_picker: 2.0.2
  simple_logger: 1.8.1
  android_intent: 2.0.2 
  flutter_social_content_share: 1.0.1
  flutter_spinkit: 5.0.0
  smooth_page_indicator: 0.3.0-nullsafety.0
  tiengviet: 0.5.0 
  pretty_json: 2.0.0
  html_character_entities: 1.0.0+1
  uni_links: 
  flutter_inappwebview: 5.3.2
  simple_tooltip: 1.0.0
  share: ^2.0.4  
  flutter_share: 2.0.0
  cupertino_icons: ^1.0.3 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: 1.2.0

flutter_native_splash:
  image: lib/base_citenco/modify/asset/image/splash.jpg
  color: "ffffff"
  fill: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/base_citenco/asset/language/
    - lib/core/asset/image/
    - lib/base_citenco/asset/image/ 
    - lib/base_citenco/modify/asset/image/ 
  # - lib/special/topup/asset/image/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: lib/base_citenco/asset/font/HelveticaNeue-UltraLight.otf
          weight: 200
        - asset: lib/base_citenco/asset/font/HelveticaNeue-UltraLightItalic.otf
          weight: 200
          style: italic
        - asset: lib/base_citenco/asset/font/HelveticaNeue-Light.otf
          weight: 300
        - asset: lib/base_citenco/asset/font/HelveticaNeue-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/base_citenco/asset/font/HelveticaNeue.otf
        - asset: lib/base_citenco/asset/font/HelveticaNeue-Italic.otf
          style: italic
        - asset: lib/base_citenco/asset/font/HelveticaNeue-Medium.otf
          weight: 500
        - asset: lib/base_citenco/asset/font/HelveticaNeue-Bold.otf
          weight: 700
        - asset: lib/base_citenco/asset/font/HelveticaNeue-BoldItalic.otf
          weight: 700
          style: italic
        - asset: lib/base_citenco/asset/font/HelveticaNeue-CondensedBold.otf
          weight: 800
        - asset: lib/base_citenco/asset/font/HelveticaNeue-CondensedBlack.otf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
